### ISSUE TITLE
Work in progress

### ISSUE THREAD

**Issue by grant** [cloudevents/conformance#15]
This repo is marked as WIP without many open GitHub issues. I'm looking at conformance testing for the CloudEvent SDKs, but I don't understand how this repo can solve that. It seems like a CLI for testing CloudEvents in yaml format?

Ideally there would be some way to use a project (maybe this one) to ensure CloudEvent SDKs can properly handle HTTP requests with CloudEvents. 

CC @grayside

**Comment by bsideup** [comment]
@grant we [just merged](https://github.com/cloudevents/conformance/pull/14) the Cucumber-based option to test the SDKs. The idea is to have a runnable spec that every SDK can run by adding a bit of a glue code.

Here are some examples of it integrated:
https://github.com/cloudevents/sdk-go/pull/474
https://github.com/cloudevents/sdk-java/pull/130

Note that the feature set is a very basic at the moment (and will definitely be extended), yet it covers quite a few aspects of the SDK.

See https://cucumber.io for more info on how to run Cucumber-based tests with your language if choice.

**Comment by grant** [comment]
Great to hear @bsideup. I'm interested in understanding the conformance of the various SDKs and to which degree end-users can rely on these libraries.

- Can we add more of a description to the repo? Is this a CLI for manual testing? Maybe remove the `Work in progress` and add issues for new features?
- I'm unfamiliar with "blue code", do we mean "glue code"?

There are only 2 GitHub issues attached to this repo. I think it would be good to add a couple more issues to see what's left to do for newcomers to this repo, but not CEs, like me. I guess I can add some, but I don't have context as to why this repo exists.

**Comment by bsideup** [comment]
@grant 

> I'm unfamiliar with "blue code", do we mean "glue code"?

Ooops! :D "glue code" of course, sorry :)

> but I don't have context as to why this repo exists.

At the moment, the repo is a mix of two things - the CLI @n3wscott created and the feature files for testing with Cucumber. You don't need the CLI to run Cucumber tests.
I will sync with Scott on how we should proceed to make the purpose of the repo more clear.

**Comment by n3wscott** [comment]
yeah I think we could have a talk about what to do with this next. 

I like the cucumber tests and I like the simple cli (i use it all the time) but it needs a couple new features. I can start making issues to track those ideas.

**Comment by grant** [comment]
Btw @n3wscott, this tool is incredibly useful. I know we're all strapped with time, but if I could do 2 things I would:

- Rename the repo from `conformance` to `cli`
- Add more and full examples to the `README.md` such that it is easy to copy/paste:
    ```sh
    cloudevents send http://localhost:8080 \
      --id abc-123 \
      --source cloudevents.conformance.tool \
      --type foo.bar \
    ```

I don't have perms for the 1st bullet, but I could make a PR for the 2nd one.

**Comment by bsideup** [comment]
> Rename the repo from `conformance` to `cli`

Or maybe create a new repo and move the CLI there while keeping the Cucumber stuff here, in `conformance`

**Comment by grant** [comment]
Again, thanks for this tool! It's useful.

I'm not too familiar with the inner working of the repo. This repo seems more like a CLI and has a couple conformance testing files.

I'd really like the CLI and would love to recommend it to devs/customers, as we use cURL right now. Not sure where the renaming discussion landed, I'd just rename the repo from `conformance` to `cli` and maybe move the small conformance part in a separate project?

This is my proposal:

- Not mark the repo as WIP: https://github.com/cloudevents/conformance/pull/16
  - Reasons in the PR.
- For renaming the repo, I think we'd need to contact @duglin to rename this repo to `cli` and create a new repo `conformance` with the conformance files, as in the [`features/` directory](https://github.com/cloudevents/conformance/tree/master/features).
  - That way, we can keep the Cucumber stuff here and the SDK scripts that use the download-and-run script should still work:
    - Commands like like this seen in SDK repos: `... https://raw.githubusercontent.com/cloudevents/conformance/master/features/http-protocol-binding.feature && cucumber-js /tmp/http-protocol-binding.feature -p default`

👍  / 👎  ?

**Comment by n3wscott** [comment]
I think the cli is an interesting usage of the repo but not the pure focus, I think we should not rename or move.
